rioxarray/rioxarray.py
sphinx/history.rst

updated writing encoding for FutureWarning

---

rioxarray/rioxarray.py
sphinx/history.rst
test/integration/test_integration_rioxarray.py

use input raster profile to write output raster profile & preserve None nodata if opened with xarray.open_rasterio

---

rioxarray/rioxarray.py
sphinx/history.rst
test/integration/test_integration_rioxarray.py

The problem with the original method is that there was no `nodata` value there yet. So, it would default to `False`. Then, when attempting to get the nodata value, it would return None even when there was a valid nodata value.

fixed setting nodata in _add_attrs_proj

---

rioxarray/__init__.py
sphinx/history.rst

Use xarray.open_rasterio for rioxarray.open_rasterio with xarray<0.12.3

---

rioxarray/rioxarray.py
sphinx/examples/convert_to_raster.ipynb
sphinx/history.rst
test/integration/test_integration_rioxarray.py

The thing that I am on the fence about is if we want to make windowed writing the default or the previous behavior the default. The windowed writing can be more memory efficient, but may not be as fast reading the entire chunk into memory. There are different scenarios. So, maybe add a `windowed=True` kwarg to turn on/off this behavior.
Side note: since the block sizes of the destination raster are created with rasterio, it should be constant across all bands, so that isn't something to worry about.

write to raster using windowed writing & add isel_window method

---

rioxarray/_io.py
sphinx/examples/convert_to_raster.ipynb
test/integration/test_integration__io.py

Makes attribute reading consistent with `xarray,open_dataset`

remove NC_GLOBAL# prefix for attributes in dataset

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

 Add support for writing scales & offsets to raster; Don't write standard raster metadata to raster tags

---

docs/history.rst
rioxarray/_io.py

Have only been able to replicate when calling `.plot()`:
```
~/scripts/rioxarray/rioxarray/_io.py in _getitem(self, key)
161                     out = np.ma.filled(out.astype(self.dtype), np.nan)
162                 if self.mask_and_scale:
--> 163                     for band in band_key:
164                         band_iii = band - 1
165                         out[band_iii] = (
TypeError: 'int' object is not iterable
```

BUG: ensure band_key is list when iterating over bands for mask and scale

---

docs/examples/convert_to_raster.ipynb
docs/examples/examples.rst
docs/examples/manage_information_loss.ipynb
docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

Note: With the addition of the `to_raster()` dataset method, decided to moved the information loss section to its own notebook.

ENH: Added to_raster method for Datasets

---

.travis.yml
docs/history.rst
rioxarray/crs.py
rioxarray/rioxarray.py
setup.py
test/integration/test_integration_rioxarray.py

Also: Add MissingCRS exceptions for 'rio.clip' and 'rio.reproject'

ENH: Use pyproj.CRS internally to manage GDAL 2/3 transition

---

docs/history.rst
rioxarray/exceptions.py
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

BUG: Use recalc=True when using transform internally & ensure stable when coordinates unavailable.

---

.github/ISSUE_TEMPLATE/bug_report.md
docs/history.rst
docs/rioxarray.rst
rioxarray/__init__.py
rioxarray/_show_versions.py
test/unit/test_show_versions.py

TODO: Change PR to master branch once #109 is merged.
```
$ python -c "import rioxarray; rioxarray.show_versions()"
rioxarray (0.0.25) deps:
rasterio: 1.1.3
xarray: 0.15.1
GDAL: 3.0.4
Other python deps:
pillow: 7.0.0
scipy: 1.4.1
pyproj: 2.6.0
System:
python: 3.8.2 | packaged by conda-forge | (default, Mar 23 2020, 18:16:37)  [GCC 7.3.0]
executable: /home/snowal/miniconda/envs/rioxarray/bin/python
machine: Linux-4.15.0-96-generic-x86_64-with-glibc2.10
```

ENH: added rioxarray.show_versions

---

rioxarray/_io.py

Following the discussion on [xarray](https://github.com/pydata/xarray/pull/3964), this PR addresses the RasterioDeprecationWarning.

RasterioDeprecationWarning

---

docs/history.rst
rioxarray/rioxarray.py
setup.py
test/integration/test_integration_rioxarray.py

Allow destination shape to be specified in reproject()

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

BUG: Make rio.shape order same as rasterio dataset shape (height, width)

---

docs/history.rst
rioxarray/_io.py
test/integration/test_integration__io.py

Fix open_rasterio() for WarpedVRT with specified src_crs

---

.isort.cfg
docs/history.rst
rioxarray/_show_versions.py
rioxarray/merge.py
test/integration/test_integration_merge.py
test/unit/test_show_versions.py

BUG: Use internal reprojection as engine for resampling window in merge

---

docs/history.rst
rioxarray/merge.py
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

With #116 and #121, I think this makes more sense. Also, the `dst_affine_width_height` version argument was pretty awkward, I don't like it, and I would be surprised if anyone was using it.

rio.reproject: change input kwarg dst_affine_width_height -> shape & transform

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

Also, found a bug in `rio.isel_window` in this process that has been addressed in this PR.

BUG: Allow clipping with disjoint geometries

---

docs/history.rst
rioxarray/rioxarray.py

Tests used to fail without this. The `isel_window` fix in #132 removed the need for this.

BUG: Remove automatically setting tiled=True for windowed writing

---

docs/history.rst
rioxarray/rioxarray.py

remove extra copies of numpy arrays

---

docs/examples/manage_information_loss.ipynb
docs/history.rst
rioxarray/_io.py
rioxarray/merge.py
rioxarray/rioxarray.py
test/conftest.py
test/integration/test_integration__io.py
test/integration/test_integration_merge.py
test/integration/test_integration_rioxarray.py

-  [x] Closes #139
- Noticed that the `sel()` operation returned an array that way sharing the coordinates of the parent for some reason ... so added `copy()` in `slice_xy()`.
- Noticed some test were using fixture instead of parametrize & weren't being run

ENH: Add write_transform to store cache in GDAL location

---

docs/examples/manage_information_loss.ipynb
docs/examples/transform_bounds.ipynb
docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

Was adding tests for `rio.slice_xy()` and realized it didn't work on a Dataset. There really isn't a reason for it not to. I then realized there are a couple of other methods/properties that could be ported over as well.

ENH: Add rio.count, rio.slice_xy(), rio.bounds(), rio.resolution(), rio.transform_bounds() to Dataset level

---

docs/examples/clip_geom.ipynb
docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

Benefits:
- Nice to have shorthand version
- Requiring the CRS has caused confusion for some in the example when the CRS is passed in from the dataset. Hopefully this will help with that.
- Matches behavior of `rio.clip_box`.

ENH: Default rio.clip to assume geometry has CRS of dataset

---

test/integration/test_integration_rioxarray.py

Different results on OSX and Windows. So, deciding to focus mainly on Linux for testing.

TST: Allow interpolate_na_veris test to xfail if not on linux

---

test/integration/test_integration__io.py

TST: Update test_nc_attr_loading with values based on recent GDAL

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

BUG: Ensure transform correct in rio.clip without coords

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_merge.py
test/integration/test_integration_rioxarray.py

This ensures the proper dtype is used for the nodata value when:
1. Reading the nodata value.
2. Writing the notata value.
3. Writing the nodata value to a raster (partially related to #113).
A warning message is added if the value changes when the dtype is converted.

BUG: Ensure the nodata value matches the dtype

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

I was originally going to remove them entirely, and then figured it would be good to leave the update instructions around for a bit longer in an exception.

Raise deprecation exception in add_spatial_ref and add_xy_grid_meta

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

Discovered the issue here: https://github.com/corteva/geocube/pull/43

BUG: Allow 'rio.write_crs' when spatial dimensions not found

---

.isort.cfg
.pre-commit-config.yaml

- https://pycqa.github.io/isort/docs/configuration/profiles/
- https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/
> If you have a step in your precommit called seed-isort-config or similar, it is highly recommend that you remove this.

LNT: Use black isort profile and remove seed-isort-config

---

setup.py
test/integration/test_integration__io.py

`unittest.mock` was added to the standard library in Python 3.3.

TST: Replace mock test dependency with unittest.mock

---

docs/history.rst
rioxarray/merge.py

BUG: Update merge to support rasterio 1.2+

---

docs/examples/dask_read_write.ipynb
docs/examples/examples.rst
rioxarray/raster_array.py
rioxarray/raster_dataset.py
rioxarray/raster_writer.py
test/integration/test_integration_rioxarray.py

ENH: Add lock kwarg to to_raster and add examples of using dask for file io

---

rioxarray/raster_array.py
rioxarray/raster_dataset.py
rioxarray/raster_writer.py
test/integration/test_integration_rioxarray.py

See #211 for additional context. The summary is that dask's `store` function allows you to pass `compute=False`. Doing this returns a `Delayed` object which can be computed later. This is really useful if your input dask arrays are used in other outputs (very common in the Satpy library where one input raster may be used for different RGB channels in various composites).
At the time of writing this only implements the functionality and includes some docstrings. Some questions and issues I ran into that I'm looking for help on:
1. Where would you like tests added for this? I could add more parametrize cases to `test_to_raster` in `test_integration_rioxarray`.
2. This, as I feared in #211, doesn't seem to work on a distributed client (multiprocess). But this doesn't actually seem to work …

ENH: Add 'compute' keyword argument to 'to_raster'

---

rioxarray/raster_array.py
test/integration/test_integration_rioxarray.py

BUG: Raise informative error in interpolate_na if missing nodata

---

.github/workflows/tests.yaml

CI: Test build with latest dependencies

---

docs/examples/read-locks.ipynb
docs/history.rst
rioxarray/_io.py
test/integration/test_integration__io.py

BUG: handle lock=True in open_rasterio and update docs

---

.github/workflows/tests.yaml

Trivial fix for the rename to `main` in dask repos

Fix upstream build by pointing to the `main` branch for dask

---

.github/workflows/tests.yaml
docs/history.rst
rioxarray/__init__.py
rioxarray/_io.py
rioxarray/raster_array.py
rioxarray/rioxarray.py
setup.py
test/conftest.py
test/integration/test_integration__io.py
test/integration/test_integration_merge.py
test/integration/test_integration_rioxarray.py

Had to add `DEP: Python 3+ and xarray 0.17+` for this to be safe to use.

REF: Store grid_mapping in encoding instead of attrs

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

BUG: Return correct transform in rio.transform with non-linear transform

---

docs/history.rst
rioxarray/merge.py
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

Discovered FIXME in docstring while working on #293.

BUG: Don't generate x,y coords in 'rio' methods if not previously there

---

rioxarray/rioxarray.py
test/integration/test_integration__io.py

BUG: Fix xy order for loading 2D non-rectilinear coords

---

rioxarray/xarray_plugin.py
test/conftest.py
test/integration/test_integration__io.py
test/integration/test_integration_rioxarray.py
test/integration/test_integration_xarray_plugin.py

Continuation of #281 
In the process of doing this:
1. I noticed `xarray.open_rasterio` was being tested instead of `rioxarray.open_rasterio`, so I updated that.
2. Added fix for missing arguments in the engine.

TST: Add more tests for rasterio engine

---

docs/history.rst
rioxarray/_io.py
rioxarray/raster_array.py
test/integration/test_integration__io.py

BUG: Use float32 for smaller dtypes when masking

---

docs/history.rst
rioxarray/_io.py
rioxarray/xarray_plugin.py
test/integration/test_integration__io.py

ENH: Added 'decode_times' and 'decode_timedelta' kwargs to 'rioxarray.open_rasterio'

---

test/conftest.py
test/integration/test_integration_rioxarray.py

https://github.com/mapbox/rasterio/blob/06a292dc5a30e483792d7083dc75da9c46ade50b/CHANGES.txt#L4-L16
```
Fix a regression introduced in 1.2.2: from_bounds() can again return Windows of zero height or width.
```

TST: Update tests for rasterio 1.2.3

---

test/conftest.py
test/integration/test_integration_xarray_plugin.py

0.18 was released a little while ago.

TST: Update backend entrypoint importorskip for xarray 0.18

---

setup.py
test/integration/test_integration__io.py

This randomly runs for 6hr+: https://github.com/corteva/rioxarray/runs/2648057792

TST: Use pytest-timeout for tests over network

---

docs/history.rst
rioxarray/_io.py
test/integration/test_integration__io.py

Separated out changes for clarity.

BUG: pass kwargs with lock=False

---

.flake8
docs/history.rst
rioxarray/_io.py
test/integration/test_integration__io.py
test/integration/test_integration__io_uri_manager.py

For the caching file manager, it closes the file handle from the cache [ref](https://github.com/pydata/xarray/blob/071da2a900702d65c47d265192bc7e424bb57932/xarray/backends/file_manager.py#L214-L222). Since there is no cache to close with, I am thinking that the class should keep track of it like the DummyFileManager [ref](https://github.com/pydata/xarray/blob/071da2a900702d65c47d265192bc7e424bb57932/xarray/backends/file_manager.py#L316). (ping @TomAugspurger in case you have thoughts on this).

BUG: Close file handle with lock=False

---

rioxarray/_io.py
rioxarray/raster_array.py
rioxarray/raster_writer.py
test/integration/test_integration__io.py

BUG: Preserve original dtype if originally complex_int16

---

.github/workflows/tests.yaml
docs/history.rst
rioxarray/raster_array.py
rioxarray/raster_dataset.py
test/integration/test_integration_rioxarray.py

This one snowballed a bit:
```
- ENH: Allow passing in kwargs to rio.reproject (issue #369)
- ENH: Allow nodata override and provide default nodata based on dtype in rio.reproject
- ENH: Add support for passing in gcps to rio.reproject (issue #339)
```

ENH: kwargs & gcps support for rio.reproject

---

docs/rioxarray.rst

The docs currently links to http://xarray.pydata.org/en/stable/internals.html#extending-xarray which is not found.
This updates that to http://xarray.pydata.org/en/stable/internals/extending-xarray.html

DOC: fix xarray page link

---

docs/history.rst
rioxarray/_io.py
test/integration/test_integration__io.py

BUG: Fix indexing error when mask_and_scale=True was combined with band dim chunking

---

docs/history.rst
rioxarray/raster_dataset.py
test/integration/test_integration_rioxarray.py

Hello, first thanks for the great extension for xarray objects!
I added an argument to raster_dataset.clip to enable clipping only some of the variables, as i am storing metadata along with raster data, which only use the time axis. Maybe this workaround is useful for others.
Using the raster_array.clip, i was not able to drop the data outside of the mask in place, but maybe there is a better way to fix this.
Cheers!

BUG: Skip non-geospatial arrays in datasets when clipping

---

docs/history.rst
rioxarray/_options.py
rioxarray/exceptions.py
rioxarray/raster_dataset.py
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

The reason this was not enabled in the past was out of an abundance of caution. There are scenarios where spatial dimensions do exist on the Dataset/DataArray but rioxarray cannot find them. In this case, we definitely want to raise an exception.
If there is only 1 dimension, then by definition spatial dims don't exist, so don't raise an error in that scenario.
However, there are some scenarios where the spatial dimensions are known, but not all of the variables have the spatial dimensions. With this PR, the user can override those scenarios.
cc: @MarkusZehner

ENH: Add option for users to skip variables without spatial dimensions

---

test/integration/test_integration_rioxarray.py

https://github.com/corteva/rioxarray/runs/3779287156?check_suite_focus=true
Seems without the WKT, the confidence for the CF generated CRS is 60% that the code is `4326`, so it returns None as 70% is the threshold.
```python
[AuthorityMatchInfo(auth_name='EPSG', code='4326', confidence=60), AuthorityMatchInfo(auth_name='IGNF', code='ANAA92G', confidence=60), AuthorityMatchInfo(auth_name='IGNF', code='ST87G', confidence=60), AuthorityMatchInfo(auth_name='OGC', code='CRS84', confidence=60), AuthorityMatchInfo(auth_name='IGNF', code='WGS84GDD', confidence=60), AuthorityMatchInfo(auth_name='IGNF', code='WGS84G', confidence=60), AuthorityMatchInfo(auth_name='EPSG', code='4762', confidence=60), AuthorityMatchInfo(auth_name='EPSG', code='6311', confidence=60), …
```

TST: test_read_crs_cf updated for rasterio 1.2.9

---

.pylintrc
docs/history.rst
rioxarray/raster_array.py
test/unit/test_unit_reproject_match.py

BUG: Force coordinates to be exactly the same in 'rio.reproject_match'

---

rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

Corrected data types, according to discussion:
https://github.com/corteva/rioxarray/discussions/474#discussioncomment-2181442

Corrected bounds and transform args to float

---

docs/history.rst
rioxarray/merge.py

BUG: Lazy load colormap through _manager.acquire() in merge

---

.github/workflows/tests.yaml
docs/history.rst
mypy.ini
rioxarray/_io.py
rioxarray/_show_versions.py
rioxarray/crs.py
rioxarray/merge.py
rioxarray/raster_array.py
rioxarray/raster_dataset.py
rioxarray/rioxarray.py
setup.cfg

TYPE: Add more type hints

---

rioxarray/raster_array.py

- Closes #508 
Docstring for default value of `inplace` argument to `RasterArray.set_nodata` is changed to match actual implemented value (True).

DOC: Fix default value for inplace argument in RasterArray.set_nodata

---

docs/history.rst
rioxarray/_show_versions.py
test/unit/test_show_versions.py

Related: https://github.com/rasterio/rasterio/pull/2447

ENH: Add additional GDAL information to rioxarray.show_versions

---

docs/history.rst
rioxarray/_io.py
test/integration/test_integration__io.py

The input arguments don't match the properties on `WarpedVRT`

BUG: Fix WarpedVRT param cache in open_rasterio

---

docs/history.rst
rioxarray/raster_array.py
test/integration/test_integration_rioxarray.py

BUG: Always generate coordinates in rio.reproject when GCPS|RPCS present

---

docs/history.rst
rioxarray/_io.py
test/integration/test_integration__io.py

This reverts commit 595b69ce7c57a8eac339b0b35233d4e52ebad689.
As shown in https://github.com/OSGeo/gdal/pull/5706, there are scenarios where the assumptions made here could cause troubles. The fix for this is safest in GDAL.

Revert "BUG: Fix subdatasets for specific Zarr driver scenario (#522)"

---

.github/workflows/tests.yaml

This CI workflow essentially checks `python -m build` to see if it builds sdist and wheel packages.

CI: add test for building sdist and wheel packages

---

.github/workflows/tests.yaml
.pre-commit-config.yaml
CONTRIBUTING.rst
MANIFEST.in
Makefile
setup.cfg
setup.py

This PR is very similar to https://github.com/corteva/geocube/pull/111
- `setup.cfg`:
- remove `bdist_universal` option
- Use `license_files` to side-step warning in `python -m build`
- Specify `long_description_content_type` to side-step warning in `twine check dist/*`
- Add dynamic version from attribute
- `setup.py` is now a basic shim file, and does nothing custom; it might be removed at some point
- Use `pytest` command instead of `py.test` ([ref](https://stackoverflow.com/a/41893170/))
- Add `make dist` target, which was referenced in the Makefile
- Add `twine check --strict dist/*` before uploading release -- also `.whl` files could and should be uploaded to PyPI
- There is no "recusive-prune" option for MANIFEST.in -- just "prune"

MNT: corrections to setup.cfg; use "pytest"; add "make dist" target

---

rioxarray/raster_array.py

Fixes https://github.com/corteva/rioxarray/issues/551 by removing unused parameters.

Removed deprecated parameters from clip_box

---

rioxarray/merge.py

In rioxarray.merge docs, the reference to "rasterio docs" is helpful but still quite vague; This adds the actual URL for them.

Add URL for rasterio-docs/merge API

---

docs/history.rst
rioxarray/_io.py
test/integration/test_integration__io.py

BUG: Fix reading cint16 files with dask

---

docs/history.rst
rioxarray/raster_array.py
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

BUG: Ensure 'rio.bounds' ordered correctly

---

docs/getting_started/crs_management.ipynb
docs/getting_started/getting_started.rst

For clarity, alert the user that `xarray.open_rasterio` is now deprecated and should not be used.

DOC: add notes to docs that xarray.open_rasterio is deprecated

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

Related:
- https://github.com/corteva/rioxarray/discussions/591
- https://github.com/pyproj4/pyproj/pull/1167

BUG: Handle CF CRS export errors in 'rio.write_crs'

---

docs/history.rst
rioxarray/_io.py
test/integration/test_integration__io.py

BUG: pass warp_extras to rasterio.vrt.WarpedVRT

---

.pylintrc
docs/history.rst
rioxarray/_io.py
test/integration/test_integration__io.py

ENH: Added band_as_variable option to open_rasterio

---

rioxarray/_io.py
rioxarray/raster_array.py
rioxarray/raster_dataset.py
rioxarray/rioxarray.py

```
note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
```
https://peps.python.org/pep-0484/
>  Type checkers should move towards requiring the optional type to be made explicit.

TYPE: Use explicit optional

---

rioxarray/xarray_plugin.py
test/integration/test_integration__io.py

BUG: Add band_as_variable to xarray plugin

---

.github/workflows/tests.yaml
docs/history.rst
rioxarray/_io.py
rioxarray/xarray_plugin.py
test/conftest.py
test/integration/test_integration__io.py
test/integration/test_integration_merge.py
test/integration/test_integration_rioxarray.py
test/integration/test_integration_xarray_plugin.py

In #606 it became evident that the files were not being closed. This fix should help users to close Datasets that have data_vars pointing to files.

BUG: Fix closing files manually

---

docs/history.rst
rioxarray/raster_dataset.py
rioxarray/raster_writer.py
test/integration/test_integration__io.py
test/integration/test_integration_rioxarray.py

BUG:dataset: Fix writing tags for bands & prevent overwriting long_name attribute

---

docs/history.rst
rioxarray/raster_array.py

BUG: Handle additional data types in `rio.reproject`

---

CONTRIBUTING.rst
Dockerfile

Found this to be useful recently with updating GDAL 3.6.1 tests.

MNT: Add dockerfile for running tests with different GDAL versions

---

rioxarray/raster_array.py

This confused me for a sec, thought I'd open a quick fix right away ;)

DOC: Fix typo in docstring of `.clip()`

---

rioxarray/rioxarray.py

I think there should be some more documentation about writing the grid_mapping to the encoding, for example to avoid the following issue: ds.to_netcdf(path, encoding=encoding) overwrites the grid_mapping encoding and results in incomplete CRS information (results in a NetCDF for which the CRS is not automatically recognized by QGIS, for example). Probably this is commonly used to set compression (accepted answer to https://stackoverflow.com/questions/40766037/specify-encoding-compression-for-many-variables-in-xarray-dataset-when-write-to).

DOC: Document grid_mapping in encoding

---

docs/history.rst
setup.cfg

Depend on numpy>=1.21 to fix installation issue

---

docs/history.rst
rioxarray/raster_writer.py

BUG: Fix usage of encode_cf_variable in rio.to_raster

---

docs/history.rst
rioxarray/merge.py

Related: https://github.com/rasterio/rasterio/pull/2740
https://github.com/corteva/rioxarray/actions/runs/4470278171/jobs/7853603260
```
FAILED test/integration/test_integration_merge.py::test_merge_arrays[True] - AttributeError: 'RasterioDatasetDuck' object has no attribute 'crs'
FAILED test/integration/test_integration_merge.py::test_merge_arrays[False] - AttributeError: 'RasterioDatasetDuck' object has no attribute 'crs'
FAILED test/integration/test_integration_merge.py::test_merge__different_crs[True] - AttributeError: 'RasterioDatasetDuck' object has no attribute 'crs'
FAILED test/integration/test_integration_merge.py::test_merge__different_crs[False] - AttributeError: 'RasterioDatasetDuck' object has no attribute 'crs'
FAILED …
```

BUG: Fix merge crs check

---

docs/getting_started/getting_started.rst

It seems like the link to "Extending xarray" has changed from http://xarray.pydata.org/en/stable/internals.html#extending-xarray (this link gives a 404 error page) to https://docs.xarray.dev/en/stable/internals/extending-xarray.html. This PR aims to update this in the file [`getting_started.rst`](https://github.com/corteva/rioxarray/blob/master/docs/getting_started/getting_started.rst).

DOC: Update link to "Extending xarray" in "getting_started.rst"

---

.pre-commit-config.yaml

The pre-commit link for isort was deprecated. This PR fixes it.

LNT: Update isort pre-commit link

---

rioxarray/__init__.py

MNT: add __all__ to top level module #680

---

.github/workflows/tests.yaml

In GDAL 3.5.3 docker repo keys for appach-arrow are stale, this will probably be fixed by rebuilding that docker image. For now we can just remove that repo before running update.
extracting build fix into a separate PR from #683 .

CI: don't fetch appache-arrow repo

---

docs/history.rst
rioxarray/_io.py
rioxarray/xarray_plugin.py
test/integration/test_integration__io.py
test/integration/test_integration_xarray_plugin.py

This PR proposes a removes the (unused) `chunks` and `cache` argument from the `open_dataset` plugin function and sends values to `open_rasterio` to get a result inline with what xarray expects. Moreover, the `preferred_chunks` encoding attribute is populated for xarray to be able to do optimized automated chunking.
The fact that `chunks` and `cache` are ignored by xarray is documented in the example here: https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html#backendentrypoint-subclassing
And the recommended usage of `preferred_chunks` is documented here: https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html#preferred-chunk-sizes
Finally, I wasn't really sure how/where to put the tests, what do you recommend?

ENH: Pass on on-disk chunk sizes as preferred chunk sizes to the xarray backend

---

.github/workflows/build_docs.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml
CONTRIBUTING.rst
Dockerfile
appveyor.yml
mypy.ini
setup.cfg

Python 3.9 is no longer supported in the scientific python ecosystem: https://scientific-python.org/specs/spec-0000/

DEP: Support Python 3.10-3.12

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

- when `gcp.z==None`, don't write z coord to geojson

More robust handling of GCPs geojson #731

---

rioxarray/_io.py

Very simple PR. I was getting deprecation warnings from `rioxarray` that originated in `xarray`. Here is an example of the warning:
```
/home/xavier/.pyenv/versions/3.9.7/envs/vetl_s2/lib/python3.9/site-packages/rioxarray/_io.py:870: DeprecationWarning: dropping variables using `drop` is deprecated; use drop_vars.
open_rasterio(  # type: ignore
```
So I simply went in and changed it. I don't have time to recreate the full dev environment, but it should work. That said, maybe someone should probably re-run you're test suite before merging. I can do it, but most likely a few days from now.

Avoiding DeprecationWarning: xr.Dataset.drop() -> xr.Dataset.drop_vars()

---

docs/history.rst
rioxarray/xarray_plugin.py
test/conftest.py
test/integration/test_integration_xarray_plugin.py

Adding to enable compatibility in `xarray.open_dataset` with other engines that require the kwarg:
```
TypeError: RasterioBackend.open_dataset() got an unexpected keyword argument 'decode_coords'
```

BUG: Add decode_coords kwarg to backend entrypoint

---

rioxarray/merge.py

Related: https://github.com/corteva/rioxarray/discussions/204#discussioncomment-269328
Failing tests: https://github.com/corteva/rioxarray/actions/runs/8126712662/job/22210778353
```
FAILED test/integration/test_integration_merge.py::test_merge_arrays[True] - AssertionError: 
Arrays are not almost equal to 7 decimals
ACTUAL: <xarray.DataArray '__xarray_dataarray_variable__' ()> Size: 8B
array(-854871110)
Coordinates:...
DESIRED: 22865733
FAILED test/integration/test_integration_merge.py::test_merge_arrays[False] - AssertionError: 
Arrays are not almost equal to 7 decimals
ACTUAL: <xarray.DataArray '__xarray_dataarray_variable__' ()> Size: 8B
array(-854871110)
Coordinates:
spatial_ref  int64 8B 0
DESIRED: 22865733
FAILED test/integration/test_integration_merge.py::test_merge__different_crs[ …
```

REF: Use rasterio.io.MemoryFile in merge

---

docs/history.rst
rioxarray/raster_dataset.py
test/integration/test_integration_rioxarray.py

BUG:reproject_match: Remove setting spatial dims on output dataset

---

docs/history.rst
rioxarray/raster_writer.py
test/integration/test_integration_rioxarray.py

Changing to be consistent with Numpy 2: https://numpy.org/neps/nep-0050-scalar-promotion.html

BUG: Raise overflow error when nodata conversion is unsafe

---

rioxarray/merge.py

Related #765
There is quite a bit of logic in `rio.to_raster` that would make this more robust.

REF:merge: Use merge path & rio.to_raster

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration__io.py
test/integration/test_integration_rioxarray.py

Note: No need to be backwards compatible because writing to netCDF didn't work previously and all other scenarios would have been in-memory only or to GeoTiff, which should work with this change.
@mraspaud

BUG: Support writing GCPs to netCDF

---

test/integration/test_integration__io.py

```
FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
```

TST: Use Dataset.sizes instead of deprecated dims

---

CONTRIBUTING.rst

Fixes a typo which caused code block rendering to fail. Also adds quotes around `.[all]` as `pip install -e .[all]` fails in some environments. E.g.:
```console
$ python -m pip install -e .[all]
zsh: no matches found: .[all]
$ python -m pip install -e ".[all]"
... # (works)
```
:point_up: I didn't add anything to `docs/history.rst` as it doesn't appear to be the convention when updating documentation.

docs: fix minor code block issue for local installation in CONTRIBUTING.rst

---

docs/history.rst
rioxarray/raster_array.py
rioxarray/raster_dataset.py
test/integration/test_integration_rioxarray.py

ENH: Add allow_one_dimensional_raster option to rio.clip_box

---

docs/getting_started/crs_management.ipynb
rioxarray/rioxarray.py

There is some confusion around when to use `write_crs` versus `set_crs`. This adds a small note to generally prefer write_crs when CRS persistence is needed. Fixes #743
One remaining nit that I would like to clarify in the documentation as well: when exactly _should_ people use `rio.set_crs()` and not `rio.write_crs()`?

MNT: recommend write_crs & deprecate set_crs

---

docs/history.rst
rioxarray/raster_array.py
rioxarray/raster_writer.py
test/integration/test_integration_rioxarray.py

```python
OverflowError: Unable to convert nodata value (3.402823466e+38) to new dtype (float32).
```
Related #782
Integer defaults changed to match: https://github.com/rasterio/rasterio/blob/9e643c3f563a679aa5400d9b1a263df97b34f9e0/rasterio/dtypes.py#L99-L112

REF:reproject: Make NaN default float nodata & update integer defaults

---

rioxarray/raster_array.py

Possibly related to: https://github.com/pydata/xarray/pull/9372
https://github.com/corteva/rioxarray/actions/runs/11151510847/job/30995110503
```
_______________ test_interpolate_na__all_nodata[open_rasterio] ________________
interpolate_na_nan = {'compare': '/home/runner/work/rioxarray/rioxarray/test/test_data/compare/MODIS_ARRAY_INTERPOLATE_NAN.nc', 'input': '/...nner/work/rioxarray/rioxarray/test/test_data/input/MODIS_ARRAY.nc', 'open': <function open_rasterio at 0x7f3fefa3b4c0>}
def test_interpolate_na__all_nodata(interpolate_na_nan):
rio_opened = "open_rasterio " in str(interpolate_na_nan["open"])
with interpolate_na_nan["open"](
interpolate_na_nan["input"], mask_and_scale=True
) as mda, interpolate_na_nan["open"](
interpolate_na_nan["compare"], mask_and_scale=True
) as mdc:
if …
```

BUG: Squeeze when using interpolate_na with extra dim

---

rioxarray/_io.py

Docstring states what the dataset's coordinates refer to without adding unnecessary detail
See https://github.com/corteva/rioxarray/issues/805 for discussion, in particular https://github.com/corteva/rioxarray/issues/805#issuecomment-2393099260

DOC: Clearer docstring for `open_rasterio`

---

test/integration/test_integration_rioxarray.py

```
FAILED test/integration/test_integration_rioxarray.py::test_reproject_match__geographic_dataset - ValueError: dst_nodata must be in valid range for destination dtype
FAILED test/integration/test_integration_rioxarray.py::test_reproject_default_nodata[int8--128] - ValueError: dst_nodata must be in valid range for destination dtype
FAILED test/integration/test_integration_rioxarray.py::test_reproject_default_nodata[uint64-18446744073709551615] - ValueError: dst_nodata must be in valid range for destination dtype
FAILED test/integration/test_integration_rioxarray.py::test_reproject_default_nodata[int64--9223372036854775808] - ValueError: dst_nodata must be in valid range for destination dtype
```

TST: Handle dtype nodata test failures

---

rioxarray/_io.py

The current specification of the previous chunks is incorrect, it always needs to sum up to the whole axis if given as tuples. What you want is an integer here.
I've recently refactored how normalize_chunks works and this will break things for you. I'll add some compat code for now, but will want to remove this at some point, so fixing it over here

BUG: Fix chunk arguments for normalize_chunks

---

rioxarray/raster_array.py

Fix typo in raster_array.py

---

docs/history.rst
rioxarray/rioxarray.py
test/integration/test_integration_rioxarray.py

BUG: Fix reproject with geoloc arrays not named xc|yc
