corteva/rioxarray

rioxarray/exceptions.py, rioxarray/rioxarray.py, sphinx/history.rst, test/integration/test_integration_rioxarray.py
=> added ability to export data array to raster

rioxarray/exceptions.py, rioxarray/rioxarray.py, sphinx/history.rst, test/integration/test_integration_rioxarray.py
=> Added methods to set and write CRS

rioxarray/rioxarray.py, sphinx/history.rst, test/integration/test_integration_rioxarray.py
=> add support for scalar coordinates in reproject (closes #15)

rioxarray/rioxarray.py, sphinx/history.rst, test/integration/test_integration_rioxarray.py
=>  added 'drop' argument for clip; fixed geometry crs reprojection in clip 

rioxarray/exceptions.py, rioxarray/rioxarray.py, sphinx/history.rst, test/integration/test_integration_rioxarray.py
=> added set_spatial_dims() method for datasets when dimensions not found

rioxarray/rioxarray.py, sphinx/history.rst, test/integration/test_integration_rioxarray.py
=> added option to do an inverted clip

rioxarray/_io.py, rioxarray/rioxarray.py, sphinx/history.rst, test/conftest.py, test/integration/test_integration_rioxarray.py
=> Add support for opening netcdf/hdf files with rioxarray.open_rasterio

rioxarray/rioxarray.py, sphinx/history.rst, test/integration/test_integration_rioxarray.py
=> added support for custom CRS with wkt attribute for datacube CRS support

sphinx/examples/convert_to_raster.ipynb, sphinx/examples/examples.rst
=> added example for converting a data array to a raster

sphinx/examples/crs_management.ipynb, sphinx/examples/examples.rst
=> added CRS management to the documenation

rioxarray/__init__.py, rioxarray/_io.py, rioxarray/rioxarray.py, sphinx/examples/convert_to_raster.ipynb, sphinx/history.rst, test/conftest.py, test/integration/test_integration__io.py, test/integration/test_integration_rioxarray.py
=> added rio.set_nodata,rio.write_nodata,rio.set_attrs,rio.update_attrs

rioxarray/_io.py, sphinx/history.rst, test/integration/test_integration__io.py
=> add 'variable' and 'group' kwargs to 'rioxarray.open_rasterio()' to allow filtering of subdatasets

rioxarray/_io.py, sphinx/history.rst, test/integration/test_integration__io.py
=>  added 'default_name' kwarg to open_rasterio for backup when the original does not exist

rioxarray/_io.py, sphinx/history.rst, test/integration/test_integration__io.py
=> make units/long_name scalar if they exist in rasterio attributes & rename descriptions to long_name

.travis.yml, rioxarray/rioxarray.py, sphinx/history.rst, test/integration/test_integration_rioxarray.py
=> fixed windowed writing to require tiled output raster

rioxarray/_io.py, sphinx/examples/convert_to_raster.ipynb, sphinx/history.rst, test/integration/test_integration__io.py
=> ignore NotGeoReferencedWarning for raster with subdatasets

rioxarray/_io.py, sphinx/examples/convert_to_raster.ipynb, sphinx/history.rst, test/integration/test_integration__io.py
For this to work, updated to load in netCDF metadata on the variable level.
=> Add support for loading in NetCDF 1D variables in 'xarray.open_rasterio()'

test/conftest.py, test/integration/test_integration_merge.py, test/integration/test_integration_rioxarray.py
=> TST: Update tests for GDAL 2.4.4

appveyor.yml
=> APPVEYOR: use python 3.7 & use python -m pip install

rioxarray/_io.py
=> reorganize io imports to match xarray

docs/history.rst, rioxarray/rioxarray.py, test/integration/test_integration_rioxarray.py
=> Added variable names to error messages for clarity

docs/history.rst, rioxarray/_io.py
=> BUG: Use assign_coords in _decode_datetime_cf

rioxarray/_io.py
=> handle future ValueError in numpy.fromstring

.travis.yml
=> Fix osx install by pinning miniconda version

docs/history.rst, rioxarray/rioxarray.py, setup.py, test/integration/test_integration_rioxarray.py
=> ENH: Use pyproj.CRS to read/write CF parameters

.travis.yml, appveyor.yml, setup.py
=> Remove pillow dependency as no longer used

test/conftest.py, test/integration/test_integration_rioxarray.py
=> TST: Update clip tests when parse_coordinates=False

docs/history.rst, rioxarray/merge.py, rioxarray/rioxarray.py, test/integration/test_integration_rioxarray.py
=> ENH: Add rio.write_coordinate_system

docs/history.rst, rioxarray/rioxarray.py, test/integration/test_integration_rioxarray.py
=> ENH: Search CF coordinate metadata to find coordinates

docs/history.rst, rioxarray/rioxarray.py, test/integration/test_integration_rioxarray.py
Addresses: https://travis-ci.com/github/corteva/geocube/jobs/354583436 :man_facepalming:
=> Deprecate add_spatial_ref and fix warning for add_xy_grid_meta

.travis.yml, CONTRIBUTING.rst, setup.py
=> Update DOC and CI for Python 3.6-3.9

docs/history.rst, rioxarray/rioxarray.py, test/integration/test_integration_rioxarray.py
=> BUG: Check all CRS are the same in the dataset in crs() method

docs/history.rst, rioxarray/merge.py, rioxarray/rioxarray.py, test/integration/test_integration_merge.py
=> ENH: Add support for merging datasets with different CRS

.github/workflows/tests.yaml, .travis.yml, README.rst, codecov.yml
=> CI: GitHub Actions

README.rst, docs/history.rst, rioxarray/raster_array.py, rioxarray/raster_writer.py, test/integration/test_integration__io.py, test/integration/test_integration_rioxarray.py
=> ENH: Add support for using dask in 'rio.to_raster'

.github/workflows/tests.yaml, docs/examples/clip_geom.ipynb, docs/history.rst, rioxarray/raster_array.py
=> ENH: Use the list version of 'transform_geom' with rasterio 1.2+

docs/history.rst, rioxarray/raster_array.py, rioxarray/raster_dataset.py
=> ENH: Support driver autodetection with rasterio 1.2+

docs/getting_started/crs_management.ipynb, docs/getting_started/getting_started.rst, docs/getting_started/nodata_management.ipynb
Only needs one in?
- minor edit
=> DOC: Grammar fixes in getting started, crs management, and nodata management

docs/history.rst, rioxarray/_io.py, rioxarray/crs.py, rioxarray/raster_array.py, rioxarray/rioxarray.py
=> REF: Reduce pyproj.CRS internal usage for speed

docs/history.rst, rioxarray/merge.py, test/integration/test_integration_merge.py
=> BUG: Handle merging 2D DataArray

docs/history.rst, rioxarray/_io.py, rioxarray/merge.py, rioxarray/raster_array.py, test/integration/test_integration__io.py
=> BUG: Compatibility changes with xarray 0.17

rioxarray/rioxarray.py
=> DOC: add example into write_crs

.github/workflows/tests.yaml, docs/history.rst, rioxarray/raster_array.py, test/integration/test_integration_rioxarray.py
=> BUG: Update to handle WindowError in rasterio 1.2.2

docs/history.rst, rioxarray/_io.py, rioxarray/raster_array.py, test/integration/test_integration__io.py, test/integration/test_integration_rioxarray.py
=> BUG: Preserve original data type for writing to disk

rioxarray/raster_writer.py, test/integration/test_integration__io.py, test/integration/test_integration_rioxarray.py
=> REF: Use encode_cf_variable when writing to raster for scale/offsets

docs/history.rst, rioxarray/raster_array.py, test/integration/test_integration_rioxarray.py
=> ENH: Add encoded kwarg to rio.write_nodata

rioxarray/xarray_plugin.py, test/integration/test_integration_xarray_plugin.py
=> BUG: Fix location of drop_variables to ensure Dataset

CONTRIBUTING.rst
=> DOC: Update contributing guide environment setup

.github/workflows/tests.yaml, rioxarray/_io.py, rioxarray/_options.py, rioxarray/raster_writer.py, rioxarray/rioxarray.py, rioxarray/xarray_plugin.py
Continuation of #193
Apparently I missed adding it to the CI. So, it was ignored for a bit.
=> LNT: pylint updates and add pylint to test workflow

docs/conf.py, rioxarray/_io.py, rioxarray/_options.py, rioxarray/merge.py, rioxarray/raster_array.py, rioxarray/raster_dataset.py
=> DOC: Add interphinx conection for xarray and rasterio

docs/history.rst, rioxarray/_io.py, test/integration/test_integration__io.py
=> BUG: Improve WarpedVRT support for gcps

docs/history.rst, test/conftest.py, test/integration/test_integration_merge.py
=> TST: Fix merge tests for rasterio 1.2.5+

test/integration/test_integration__io.py
=> TST: skip cint tests with rasterio < 1.2.4

docs/history.rst, rioxarray/_io.py
=> BUG: Remove duplicate acquire in open_rasterio

docs/history.rst, rioxarray/raster_dataset.py, test/integration/test_integration_rioxarray.py
=> BUG: Fix exporting dataset to raster with non-standard dimensions

docs/history.rst, rioxarray/rioxarray.py, test/integration/test_integration_rioxarray.py
=> ENH: Add pad option to rio.isel_window

.github/workflows/tests.yaml
https://github.com/corteva/rioxarray/runs/3203212255
ImportError: libpoppler.so.91: cannot open shared object file: No such file or directory
=> CI: channel priority strict for installation

.github/workflows/build_docs.yaml, .github/workflows/tests.yaml, appveyor.yml
=> CI: Update build with prepend conda-forge & strict

test/integration/test_integration__io.py
- Related to https://github.com/mapbox/rasterio/issues/2290
- Tests updated
=> TST: Use EPSG codes for tests instead of PROJ strings

rioxarray/_io.py, rioxarray/crs.py, rioxarray/raster_array.py, setup.py, test/conftest.py, test/integration/test_integration__io.py, test/integration/test_integration_rioxarray.py
https://www.python.org/dev/peps/pep-0632/
=> DEP: Replace distutils with packaging

docs/history.rst, rioxarray/rioxarray.py, test/integration/test_integration__io.py, test/integration/test_integration_rioxarray.py
https://gis.stackexchange.com/questions/411861/cannot-convert-geotiff-file-into-netcdf-file-in-python-the-file-is-empty
=> BUG: Handle transforms with rotation

rioxarray/_io.py, rioxarray/_show_versions.py, rioxarray/raster_dataset.py, rioxarray/rioxarray.py
https://github.com/corteva/rioxarray/runs/3635074374?check_suite_focus=true
=> LNT: handle pylint's latest complaints

.github/workflows/tests.yaml, docs/history.rst, rioxarray/raster_array.py, rioxarray/raster_dataset.py, setup.py, test/integration/test_integration_rioxarray.py
=> DEP: Make scipy an optional dependency

.github/workflows/tests.yaml
https://github.com/pydata/xarray/issues/5944
=> CI: pin xarray=0.19 until entrypoints bug resolved

docs/examples/clip_geom.ipynb
=> DOC: Discrepancy between clip methods

.github/workflows/tests.yaml
=> CI: Remove xarray version pin

.github/workflows/tests.yaml, CONTRIBUTING.rst, appveyor.yml, docs/history.rst, setup.py
=> DEP: Drop Python 3.7 support

setup.py
=> DEP: Remove linting deps in dev

rioxarray/_io.py
=> Fix gcps validity check for older versions of rasterio

rioxarray/raster_writer.py, test/conftest.py
=> REF: remove crs from UNWANTED_RIO_ATTRS

docs/getting_started/nodata_management.ipynb
=> DOC: Add bullet for masked data nodata logic in nodata management

.github/workflows/tests.yaml
Related: https://github.com/rasterio/rasterio/pull/2344
=> CI: Use GDAL Docker image for tests

rioxarray/_io.py
=> CLN: Remove _io._rio_transform

setup.py
Related: https://github.com/pyproj4/pyproj/pull/683
=> CLN: Update get_version to raise SystemExit and use pathlib

.github/workflows/tests.yaml, test/conftest.py
https://github.com/rasterio/rasterio/issues/2310#issuecomment-1104698511
=> TST: rasterio==1.3a4 for Python 3.10 and other test updates

docs/conf.py, docs/getting_started/crs_management.ipynb, docs/getting_started/getting_started.rst
=> DOC: Add docs for persisting spatial dimensions

rioxarray/raster_writer.py, rioxarray/rioxarray.py
Related:
- https://github.com/python/mypy/issues/1106
- https://github.com/pyproj4/pyproj/pull/1047
=> TYPE: remove query_utm_crs_info ignore & ignore is_dask_collection

docs/history.rst, rioxarray/_io.py, test/integration/test_integration__io.py
=> BUG: Fix subdatasets for specific Zarr driver scenario

rioxarray/raster_array.py, rioxarray/raster_dataset.py
=> DOC: Add docstring for argument recalc_transform in to_raster

.github/workflows/tests.yaml
https://github.com/rasterio/rasterio/issues/2310#issuecomment-1168043910
=> DEP: rasterio==1.3b3

docs/history.rst, rioxarray/_io.py, test/integration/test_integration__io.py
=> BUG: Fix reading file handle with dask

docs/history.rst, rioxarray/_io.py, test/integration/test_integration__io.py
=> BUG: Allow reading from io.BytesIO

docs/history.rst, rioxarray/_io.py, test/integration/test_integration__io.py
=> BUG: Fix mask_and_scale data load after .sel

.github/workflows/tests.yaml, docs/history.rst, rioxarray/raster_array.py
Related: https://github.com/rasterio/rasterio/pull/2634
=> BUG: Add GDAL 3.6 driver auto-select fix

rioxarray/_io.py, rioxarray/_show_versions.py, rioxarray/crs.py, rioxarray/merge.py, rioxarray/raster_array.py, rioxarray/raster_dataset.py, rioxarray/raster_writer.py, rioxarray/rioxarray.py, test/conftest.py, test/integration/test_integration__io.py
Related: https://github.com/corteva/rioxarray/issues/582
```
pyupgrade --py39-plus `find . -name "*.py" -type f`
```
=> REF: Upgrade to Python 3.9+ codestyle

docs/history.rst, rioxarray/_io.py, test/integration/test_integration__io.py
=> BUG: Fix WarpedVRT in open_rasterio when band_as_variable=True

.github/workflows/tests.yaml, Dockerfile
=> CI: Use ghcr.io for osgeo/gdal docker images

docs/history.rst, rioxarray/_io.py, rioxarray/raster_array.py, rioxarray/raster_writer.py, test/integration/test_integration__io.py
=> BUG: Remove tags with metadata added by rasterio in open_rasterio

.github/workflows/tests.yaml, Dockerfile, test/conftest.py, test/integration/test_integration__io.py, test/integration/test_integration_rioxarray.py
Related:
- https://github.com/OSGeo/gdal/issues/7695
- https://github.com/OSGeo/gdal/releases/tag/v3.6.4
=> CI: Update to GDAL 3.6.4

docs/history.rst, rioxarray/rioxarray.py
https://github.com/geoxarray/geoxarray/issues/24#issuecomment-1626004813
=> BUG: Fix setting spatial dims internally during propagation

.github/workflows/tests.yaml
https://github.com/pandas-dev/pandas/issues/54253
=> CI: Update location of nightly wheels

.pylintrc, rioxarray/rioxarray.py, setup.cfg, test/integration/test_integration_rioxarray.py
- https://github.com/corteva/rioxarray/pull/723
- Python 3.10 wheels were added in pyproj 3.3.
=> DEP: Update to pyproj 3.3+

.github/workflows/tests.yaml, docs/history.rst, setup.cfg
https://scientific-python.org/specs/spec-0000/
=> DEP: xarray 2022.3.0+ & numpy 1.23+

docs/getting_started/crs_management.ipynb
=> DOC: Fix typo

docs/examples/read-locks.ipynb
=> DOC: Fix spelling of repeatedly

docs/examples/interpolate_na.ipynb
=> DOC: Fix spelling of missing

docs/history.rst, rioxarray/rioxarray.py, test/integration/test_integration_rioxarray.py
=> BUG:reproject: Allow rotated rasters

rioxarray/merge.py
Not actually a possessive, something like this?
=> DOC: multiple types

.github/workflows/tests.yaml, environment.yml
https://github.com/conda-forge/rasterio-feedstock/issues/303
=> CI: Add libgdal for micromamba tests

rioxarray/raster_array.py, rioxarray/raster_dataset.py
=> REF: Relax positional arguments requirement for clip

.github/workflows/tests.yaml, docs/history.rst, rioxarray/_io.py, rioxarray/merge.py, test/integration/test_integration_merge.py
=> BUG:merge: Fix merging masked & scaled data

rioxarray/_io.py
=> DOC: Update warning message for differing scales in rasterio attributes

docs/getting_started/nodata_management.ipynb
=> DOC: Fix spelling of "Unmasked"

rioxarray/raster_array.py, rioxarray/raster_dataset.py, test/integration/test_integration_rioxarray.py
Related: https://github.com/dask/dask/pull/11844/
From: https://github.com/corteva/rioxarray/actions/runs/14318351374/job/40129638475
```
>           assert isinstance(delayed, Delayed)
E           assert False
E            +  where False = isinstance(dask.array<store-map, shape=(1, 200, 200), dtype=int16, chunksize=(1, 200, 200), chunktype=numpy.ndarray>, Delayed)
```
=> TST Address dask delayed changes
